
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import nodemailer from "npm:nodemailer@6.9.7";

declare const Deno: any;

// You will set these in your Supabase Dashboard or via CLI
const GMAIL_USER = Deno.env.get('GMAIL_USER');
const GMAIL_APP_PASSWORD = Deno.env.get('GMAIL_APP_PASSWORD');

serve(async (req) => {
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  };

  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { email, name, caseId, brief } = await req.json();

    if (!GMAIL_USER || !GMAIL_APP_PASSWORD) {
      throw new Error("Missing GMAIL configuration (User or App Password). Please set these in your Supabase secrets.");
    }

    // Configure Nodemailer for Gmail
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: GMAIL_USER,
        pass: GMAIL_APP_PASSWORD,
      },
    });

    const htmlContent = `
      <div style="font-family: serif; color: #1e293b; max-width: 600px; margin: 0 auto; padding: 40px; border: 1px solid #e2e8f0;">
        <div style="text-align: center; border-bottom: 2px solid #cca43b; padding-bottom: 20px; margin-bottom: 30px;">
          <h1 style="margin: 0; color: #0f172a;">Khalwale & Co</h1>
          <p style="margin: 5px 0 0 0; font-size: 12px; text-transform: uppercase; color: #cca43b; letter-spacing: 2px;">IP Division</p>
        </div>
        
        <p>Dear ${name},</p>
        <p>Please find attached the executive summary generated by our intake counsel regarding your recent submission.</p>
        
        <div style="background: #f8fafc; padding: 20px; border-radius: 8px; border-left: 4px solid #cca43b; margin: 20px 0;">
          <strong>Case ID:</strong> ${caseId}<br/>
          <strong>Date:</strong> ${new Date().toLocaleDateString()}
        </div>

        <h3>Counsel's Preliminary Findings:</h3>
        <div style="white-space: pre-wrap; font-family: sans-serif; font-size: 14px; line-height: 1.6;">
          ${brief}
        </div>

        <p style="margin-top: 40px; font-size: 12px; color: #64748b; text-align: center;">
          This is an automated transmission from a secure legal system.<br/>
          Replies to this email are routed directly to the Senior Partner at <strong>${GMAIL_USER}</strong>.
        </p>
      </div>
    `;

    const mailOptions = {
      from: `Khalwale Legal <${GMAIL_USER}>`,
      to: email,
      cc: GMAIL_USER, // Copy the firm
      replyTo: GMAIL_USER,
      subject: `Legal Briefing: Case #${caseId}`,
      html: htmlContent,
    };

    // Send the email using a promise wrapper
    await new Promise((resolve, reject) => {
      transporter.sendMail(mailOptions, (error: any, info: any) => {
        if (error) {
          console.error("SMTP Error:", error);
          reject(error);
        } else {
          console.log("SMTP Success:", info.response);
          resolve(info);
        }
      });
    });

    return new Response(JSON.stringify({ message: "Email dispatched via Gmail SMTP" }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 200,
    });

  } catch (error) {
    console.error("Function Error:", error.message);
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 500,
    });
  }
});
